title: Color
url: https://color.app.5ls.de

collections:
  color:
    output: true
    permalink: /:name


defaults:
  - scope:
      path: ""
      type: "color"
    values:
      layout: "main"
 

exclude:
  - CNAME

timezone: Europe/Berlin